### ISSUE TITLE
Fantastic code

### ISSUE THREAD

**Issue by tomaroberts** [mercure-imaging/mercure-totalsegmentator#1]
Some cracking code in here, whoever wrote it.

**Comment by jmsocallaghan** [comment]
Thanks for bringing this to our attention @tomaroberts, we've now added an acknowledgments section to the repo with the following text:

MAP operators and code adapted from GSTT-CSC TotalSegmentator-AIDE repository: https://github.com/GSTT-CSC/TotalSegmentator-AIDE
